name: 'Create a GitHub Release'

on:
  workflow_call:
    secrets:
      app_id:
        description: GitHub App ID for releases
        required: true

      app_private_key:
        description: GitHub App private key for releases
        required: true

jobs:
  workflow:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: HBK-MicroStrain-Internal/actions/checkout@main
        with:
          app_id: ${{ secrets.app_id }}
          app_private_key: ${{ secrets.app_private_key }}

      - name: 'Generate Release GitHub App Token'
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.app_private_key }}

      - name: 'Download Release Artifacts'
        uses: actions/download-artifact@v8.0.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          path: ./release-artifacts

      - name: 'Extract Release Version'
        id: project-version
        uses: HBK-MicroStrain-Internal/actions/cmake-project-version@main

      - name: 'Extract Release Notes'
        id: extract-notes
        uses: mindsers/changelog-reader-action@v2
        with:
          path: CHANGELOG.md
          version: v${{ steps.project-version.outputs.version }}

      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          tag_name: v${{ steps.project-version.outputs.version }}
          target_commitish: ${{ github.sha }} # Ensures the tag is created on the current commit
          files: ./release-artifacts/**/*
          body: ${{ steps.extract-notes.outputs.changes }}

      - name: 'Create Release Sync Pull Request To Develop'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |          
          release_version="v${{ steps.project-version.outputs.version }}"

          gh pr create \
            --base develop \
            --head release/${release_version} \
            --title "Sync develop with release ${release_version}" \
            --body "${{ steps.extract-notes.outputs.changes }}"
